# Generated by Django 5.1.3 on 2025-01-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selleritems',
            options={'verbose_name': 'Sellers Item', 'verbose_name_plural': 'Sellers Items'},
        ),
    ]
