# Generated by Django 5.1.3 on 2025-01-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyeritems',
            options={'verbose_name': 'Buyers Item', 'verbose_name_plural': 'Buyers Items'},
        ),
    ]
