# Generated by Django 5.1.3 on 2025-01-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagestatus',
            options={'verbose_name': 'Messages Status', 'verbose_name_plural': 'Messages Status'},
        ),
    ]
