# Generated by Django 5.1.3 on 2026-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0004_alter_blockeduser_options_message_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
