# Generated by Django 5.1.3 on 2026-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0005_message_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='message_videos/'),
        ),
    ]
