# Generated by Django 5.1.3 on 2026-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0007_alter_message_image_alter_message_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='product_type',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
