# Generated by Django 5.1.3 on 2026-09-27 18:53

import agro_marketplace.agro_messages.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0008_message_product_id_message_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=agro_marketplace.agro_messages.storages.LocalMessageImageStorage(), upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, storage=agro_marketplace.agro_messages.storages.LocalMessageVideoStorage(), upload_to='', verbose_name='video'),
        ),
    ]
