# Generated by Django 5.1.3 on 2026-09-30 20:13

import agro_marketplace.agro_messages.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0010_messageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(storage=agro_marketplace.agro_messages.storages.LocalMessageAttachmentStorage(), upload_to=''),
        ),
    ]
